node {
	def props = readJSON file: 'Deployment_Automation/HelperJobs/HelperJob1/test.json'
        def keys = props.keySet() as List
	properties (
	[
        	parameters (
			 [ choice(name: 'CHOICE', choices: keys, description: 'Pick something') ]
			)
	])

	//checkout scm
	stage ('Stage 1')
	{
		echo 'testt testsetestest'
	}
}

/*pipeline 
{
	agent any
			def props = readJSON file: 'Deployment_Automation/HelperJobs/HelperJob1/test.json'
			def keys = props.keySet() as List

	properties

	parameters {
	        //def props = readJSON file: 'Deployment_Automation/HelperJobs/HelperJob1/test.json'
        	//def keys = props.keySet() as List

		//choiceParam('OPTION', keys)
		choice(name: 'CHOICE', choices: keys, description: 'Pick something')
	}
	stages {
		stage('Stage 1') {
			steps {
				echo 'This is a cool file'		
			}
		}
	}
}*/
