node {
	def props = readJSON file: 'Deployment_Automation/HelperJobs/HelperJob1/test.json'
	def keys = props.keySet() as List
}

pipeline 
{
	agent any
	//checkout scm
        def props = readJSON file: 'Deployment_Automation/HelperJobs/HelperJob1/test.json'
        def keys = props.keySet() as List


	parameters {
		//choiceParam('OPTION', keys)
		choice(name: 'CHOICE', choices: keys, description: 'Pick something')
	}
	stages {
		stage('Stage 1') {
			steps {
				echo 'This is a cool file'		
			}
		}
	}
}
