

node {
    checkout scm
    jobDsl scriptText: 'job("example-2")'

    jobDsl targets: ['Deployment_Automation/create_jobs/create_deployment_automation.groovy'].join('\n'),
           removedJobAction: 'DELETE',
           removedViewAction: 'DELETE',
           lookupStrategy: 'SEED_JOB',
           additionalParameters: [message: 'Hello from pipeline', credentials: 'SECRET']
}
