node('DEPLOY')
{
	stage ('Checkout SCM')
	{
		checkout scm
	}

	def my_config = [:]
	def keys = []	

	try
	{
		my_config = readJSON file: 'Deployment_Automation/config/MyConfig.json'
	        keys = my_config['env_info'].keySet() as List
	} 
	catch (Exception ex)
	{
		println("Exception: ${ex}")
		keys = []
	}

	keys = ['Not Selected'] + keys

	println ("Config ${my_config}")
	println ("Keys: ${keys}")
        
        properties (
        [
                parameters (
                         [ choice(name: 'CHOICE', choices: keys, description: 'Pick something') ]
                        )
        ])

	def host_a = "NO_HOST"
	def host_b = "NO_HOST"
	def host_c = "NO_HOST"	

	try
	{
		println("Selected '${CHOICE}'")
		host_a = my_config['env_info']["${CHOICE}"]['hosts']['type_a']
		host_b = my_config['env_info']["${CHOICE}"]['hosts']['type_b']
		host_c = my_config['env_info']["${CHOICE}"]['hosts']['type_c']
		println ("Host_A: ${host_a}")
	}
	catch (Exception ex)
	{
		println ("Caught Ex: ${ex}")
	}


	/*stage ('Step 1')
	{
		println ('Test Step 1')
	}*/

	for (i=0;i<10;i++)
	{
		if (i < 3 && i >= 0)
		{
			stage ("Step ${i} - Group A")
			{
				println ("This is step ${i} - ${CHOICE} - ${host_a}")
			}
		}
		else if (i > 6 && i >=3)
		{
			stage ("Step ${i} - Group B")
                        {
                                println ("This is step ${i} - ${CHOICE} - ${host_b}")
                        }
		}
		else
		{
			stage ("Step ${i} - Group C")
                        {
                                println ("This is step ${i} - ${CHOICE} - ${host_c}")
                        }
		}
	}
}
