node('DEPLOY')
{
	stage ('Checkout SCM')
	{
		checkout scm
	}

	def my_config = [:]
	def keys = []	

	try
	{
		my_config = readJSON file: 'Deployment_Automation/config/MyConfig.jsona'
	        keys = my_config['env_info'].keySet() as List
	} 
	catch (Exception ex)
	{
		println("Exception: ${ex}")
		keys = []
	}

	keys = ['Not Selected'] + keys

	println ("Config ${my_config}")
	println ("Keys: ${keys}")
        
        properties (
        [
                parameters (
                         [ choice(name: 'CHOICE', choices: keys, description: 'Pick something') ]
                        )
        ])


	stage ('Step 1')
	{
		println ('Test Step 1')
	}
}
