node('DEPLOY')
{
	stage ('Checkout SCM')
	{
		checkout scm
	}

	def my_config = [:]
	def keys = []	

	try
	{
		my_config = readJSON file: 'Deployment_Automation/config/MyConfig.json'
	        keys = my_config['env_info'].keySet() as List
	} 
	catch (Exception ex)
	{
		println("Exception: ${ex}")
		keys = []
	}

	keys = ['Not Selected'] + keys

	println ("Config ${my_config}")
	println ("Keys: ${keys}")
        
        properties (
        [
                parameters (
                         [ choice(name: 'CHOICE', choices: keys, description: 'Pick something') ]
                        )
        ])

	def host_a = "NO_HOST"
	
	try
	{
		host_a = my_config['env_info']['${CHOICE}']['hosts']['type_a']
	}
	catch (Exception ex)
	{
		println ("Caught Ex: ${ex}")
	}


	/*stage ('Step 1')
	{
		println ('Test Step 1')
	}*/

	for (i=0;i<10;i++)
	{
		stage ("Step ${i}")
		{
			println ("This is step ${i} - ${CHOICE} - ${host_a}")
		}
	}
}
